# Configuration for MK Auto-Deploy System
defaults:
  verification:
    timeout: 30000
    httpTimeout: 10000
    cleanupVerificationFile: true
    retries: 3
    retryDelay: 2000
  excludes:
    - "*.tmp"
    - "*.log"
    - "**/*.map" # exclude source maps from deploy
    - ".git/**"
    - ".gitignore"
    - "node_modules/**"
    - ".env*"
    - "_backup*/**"
    - "_documentation/**"
    - "_deployment-system/**"
    - "migrate-theme-colors.ps1" # theme migration scripts
    - "theme-migration.ps1" # theme migration scripts
    - "**/phpinfo.php" # diagnostic files
    - "**/pdo-check.php" # diagnostic files
    - "DESIGN-SYSTEM.md" # internal docs

# Deployment targets
# Path Logic:
# - remoteRoot: Base FTP directory (e.g., "/11seconds.de/httpdocs")
# - project.parts.remotePath: Subdirectory within remoteRoot for FTP (e.g., "/admin")
# - project.parts.webPath: Web URL path for verification (e.g., "/admin")
# - FTP Final path: remoteRoot + remotePath = "/11seconds.de/httpdocs/admin"
# - Web Final URL: https://domain + webPath = "https://11seconds.de/admin"
#
# IMPORTANT DEPLOYMENT POLICY:
# All admin files MUST be deployed to the server path /httpdocs/admin.
# The deploy tools in this repository enforce that remote admin target and
# documentation must state this explicitly. Do NOT place package.json into
# /httpdocs on the server as that may trigger unwanted runtime detection.
#
#
# Environment Variables Required:
# - FTP_USER: FTP username (e.g., "k302164_11s")
# - FTP_PASSWORD: FTP password
targets:
  production:
    method: ftp
    remoteRoot: "/httpdocs" # FTP web root at host (use absolute path to avoid double domain)
    domain: "11seconds.de"
    ftp:
      host: "ftp.11seconds.de"
      user: "${FTP_USER}"
      password: "${FTP_PASSWORD}"
      timeout: 30000

  local:
    method: copy
    localPath: "c:\\Users\\mako1\\OneDrive\\Dokumente\\GitHub\\11S\\.local-deploy\\httpdocs"
    domain: "localhost:3010"

# Projects configuration
projects:
  web:
    # Source and build
    localSource: "c:\\Users\\mako1\\OneDrive\\Dokumente\\GitHub\\11S\\web"
    localBuild: "c:\\Users\\mako1\\OneDrive\\Dokumente\\GitHub\\11S\\web\\httpdocs" # This project uses httpdocs as build artifact
    buildCommand: "npm ci && npm run build && if exist build (xcopy build\\* httpdocs\\ /s /e /y /i >NUL)"

    parts:
      # Deploy the compiled SPA from httpdocs folder
      app-httpdocs:
        basePath: "c:\\Users\\mako1\\OneDrive\\Dokumente\\GitHub\\11S\\web\\httpdocs"
        include:
          - "**/*"
        exclude:
          - "**/*.map"
          - "admin/**"
          - "api/**"
        remotePath: "/"
        webPath: "/"

      # 1:1 mirror of /admin directory from repo to /admin on host
      admin:
        basePath: "c:\\Users\\mako1\\OneDrive\\Dokumente\\GitHub\\11S\\admin"
        include:
          - "**/*"
        exclude:
          - "**/phpinfo.php"
          - "**/pdo-check.php"
        remotePath: "/admin"
        webPath: "/admin"

      # 1:1 mirror of /api directory
      api:
        basePath: "c:\\Users\\mako1\\OneDrive\\Dokumente\\GitHub\\11S\\api"
        include:
          - "**/*"
        remotePath: "/api"
        webPath: "/api"

      # 1:1 mirror of /static directory
      static:
        basePath: "c:\\Users\\mako1\\OneDrive\\Dokumente\\GitHub\\11S\\static"
        include:
          - "**/*"
        remotePath: "/static"
        webPath: "/static"

      # Root-level PHP (only files at repo root)
      root-php:
        basePath: "c:\\Users\\mako1\\OneDrive\\Dokumente\\GitHub\\11S"
        include:
          - "*.php"
        remotePath: "/"
        webPath: "/"

      # Root-level assets that may need cache-busting (service worker, robots)
      root-assets:
        basePath: "c:\\Users\\mako1\\OneDrive\\Dokumente\\GitHub\\11S"
        include:
          - "sw.js"
          - "kill-sw.html"
          - "robots.txt"
          - "asset-manifest.json"
        remotePath: "/"
        webPath: "/"

      # Example of pinning a special file with custom remote path (disabled by default)
      # package-json-example:
      #   basePath: "c:\\Users\\mako1\\OneDrive\\Dokumente\\GitHub\\11S"
      #   files:
      #     - { local: "package.json", remotePath: "/_meta/package.json", webPath: "/_meta/package.json" }

    verify:
      enabled: true
      fileTemplate: "deploy-verify-{timestamp}.html"
      urlTemplate: "https://{domain}/{file}"

  # Example configurations for other frameworks
  # Example templates can be re-enabled as needed
